>P1;1hpi1DOMAK

---MERLSEDDPAAQALEYRHDAS-----SVQHPAYE-EGQTCLNC-LLYTDAS--AQDW
GPCSV--FPGKL-VSANGWCTAWVAR--
*
>P1;1hip1DOMAK

SAPANAVAADNATAIALKYNQDATKSERVAAARPGLPPEEQHCADCQFMQADAAGATDEW
KGCQL--FPGKL-INVNGWCASWTLKAG
*
>P1;2hipa1DOMAK

----EPRAEDG---HAHDYVNEAAD----ASGHPRYQ-EGQLCENC-AFWGEAV--QDGW
GRCTHPDFDEVL-VKAEGWCSVYAPAS-
*
>P1;1isua1DOMAK

-------GTNAAMRKAFNYQDTAK--------------NGKKCSGCAQFVPGAS--PTAA
GGCKV--IPGDNQIAPGGYCDAFIVKK-
*
