>256bb-1-DOMAK | (cluster A) sequence |  133 residues
---------adLEDNMETLNDNLKVIEK------adNAAQVKDALTKMRAAA-lDAQKAtppkle---------dkspds
peMKDFRHGFDILVGQIDDALKLANEGKVKEAQAAAEQLKTTRNAYHQKYR--
>1bbha-1-DOMAK | (cluster B) sequence |  133 residues
aglspeeqietRQAGYEFMGWNMGKIKAnl--egeyNAAQVEAAANVIAAIAnsGMGALygpgtdknvgdvktrvkpeff
qnMEDVGKIAREFVGAANTLAEVAATGEAEAVKTAFGDVGAACKSCHEKYRak
>1cgo-1-AUTO.1 | (cluster B) sequence |  133 residues
xfakpedavkyRQSALTLMASHFGRMTPvvkgqapyDAAQIKANVEVLKTLT-aLPWAAfgpgtegg------darpeiw
sdAASFKQKQQAFQDNIVKLSAAADAGDLDKLRAAFGDVGASCKACHDAYRk-
>1cgn-1-AUTO.1 | (cluster B) sequence |  133 residues
xfakpedavkyRQSALTLMASHFGRMAPvvkgqapyDAAQIKANVEVLKTLT-aLPWAAfgagtegg------darpeiw
sdAAGFKQKQQAFQDNIVKLSAAADAGDLDKLRAAFGDVGASCKACHDSYRk-
