>1inel-1-DOMAK | (cluster A) sequence |  111 residues
-AVVTQESALTTSPGETVTLTCRSSTGAVTTSNYANWVQEKPDHLFTGLIGGTNNRAPGVPARFSGSLIGDKAALTITGA
QTEDEARYFCALWYsNLWVFGGGTKLTVL--
>1mfa-1-DOMAK | (cluster B) sequence |  111 residues
qIVVTQESALTTSPGETVTLTCRSSTGTVTSGNHANWVQEKPDHLFTGLIGDTNNRAPGVPARFSGSLIGDKAALTITGA
QPEDEAIYFCALWSnNHWIFGGGTKLTVLgq
>1mfbl-1-DOMAK | (cluster B) sequence |  111 residues
qAVVTQESALTTSPGETVTLTCRSSTGTVTSGNHANWVQEKPDHLFTGLIGDTNNRAPGVPARFSGSLIGDKAALTITGA
QPEDEAIYFCALWCnNHWIFGGGTKLTVLg-
