>1pne-1-AUTO.2 | (cluster A) sequence |  142 residues
aGWNAY-iDNLMADGTCQDAAIVGykdspSVWAAVPGktfvNITPAEVGILV--gkdRSSFFVNGLTLGGQKCSVIRDSl
lqdgefTMDLRtkstggaptFNITVTMTAKTLVLLMGKEgVHGGMINKKCYEMASHLRRSQY
>2acg-1-DOMAK | (cluster B) sequence |  142 residues
-SWQTYvdTNLVGTGAVTQAAIIG--hdgNTWATSAG---fAVSPANGAALAnafkdATAIRSNGFELAGTRYVTIRAD-
----drSVYGKk------gsAGVITVKTSKAILIGVYNEkIQPGTAANVVEKLADYLIGQGF
>1acf-1-DOMAK | (cluster B) sequence |  142 residues
-SWQTYvdTNLVGTGAVTQAAILG--ldgNTWATSAG---fAVTPAQGTTLAgafnnADAIRAGGFDLAGVHYVTLRAD-
----drSIYGKk------gsSGVITVKTSKAILVGVYNEkIQPGTAANVVEKLADYLIGQGF
