>1napc-1-AUTO.1 | (cluster A) sequence |  66 residues
---RCLCIKTTSGIHPKNIQSLEVIGKGTHCNQVEVIATLKDGRKICLDPDAPRIKKIVQKKLAgd
>1plfb-1-DOMAK | (cluster B) sequence |  66 residues
edlQCVCLKTTSGINPRHISSLEVIGAGLHCPSPQLIATLKTGRKICLDQQNPLYKKIIKRLLKs-
>1rhpc-1-AUTO.1 | (cluster B) sequence |  66 residues
-dlQCLCVKTTSQVRPRHITSLEVIKAGPHCPTAQLIATLKNGRKICLDLQAPLYKKIIKKLLEs-
