>1dpc-1-AUTO.1 | (cluster A) sequence |  238 residues
------mtrlmqigatnlhrswlnvpHVTQFESADITELEAFRVAqkavaekagvklTVLPLLLKACAYLLKELPDFNSS
LapsgqaLIRKKYVHIGFAVDt--pdgLLVPVIRNVdqkSLLQLAAEAAELAEKARskkl--gadamqgaCFTISSLgHI
GG-TAFTpiv---napeVAILGVSKASMQpvwdgkafqpRLMLPLSLSYDHRVIDGAAAARFTKRLGDLLADiraill
>1cia-1-AS | (cluster B) sequence |  238 residues
mnytkfdvknwvrrehfefyrhrlpcGFSLTSKIDITTLKKSLDD---------sayKFYPVMIYLIAQAVNQFDELRMA
Ikd--deLIVWDSVDPQFTVFhqetetFSALSCPYS--sDIDQFMVNYLSVMERYKsdtklfpqgvtpenHLNISAL-PW
VNfDSFNlnvanftdyfAPIITMAKYQQE--------gdRLLLPLSVQVHQAVCDGFHVARFINRLQELCNS--klk-
>1qca-1-AS | (cluster B) sequence |  238 residues
mnytkfdvknwvrrehfefyrhrlpcGFSLTSKIDITTLKKSLDD---------sayKFYPVMIYLIAQAVNQFDELRMA
Ikd--deLIVWDSVDPCFTVFhqetetFSALSCPYS--sDIDQFMVNYLSVMERYKsdtk--lfpqgpenHLFISAL-PW
VNfDSFNlnvanftdffAPVITMAKYQQE--------gdRLLLPLSVQVHHAVCDGFHVARFINRLQELCNS--klk-
