>2bb2-1-DOMAK | (cluster A) sequence |  95 residues
--lnPKIIIFEQENFQGHSHE-lNGPCPNL-ketgvEKAGSVLVQAGPWVGYEQANCKGEQFVFEKGEYPRWDSWtssrr
TDSLSSLRPIKvdsq
>1gcs-2-AS | (cluster B) sequence |  95 residues
htgtFRMRIYERDDFRGQMSE-iTDDCPSLqdrfhlTEVHSLNVLEGSWVLYEMPSYRGRQYLLRPGEYRRYLDW--gam
NAKVGSLRRVMdfy-
>1gcs-1-AS | (cluster B) sequence |  95 residues
----GKITFYEDRGFQGHCYE-cSSDCPNL-qpyf-SRCNSIRVDSGCWMLYERPNYQGHQYFLRRGDYPDYQQW--mgf
NDSIRSCRLIPq---
>2bb2-2-DOMAK | (cluster B) sequence |  95 residues
---eHKITLYENPNFTGKKMEviDDDVPSFhahgyqEKVSSVRVQSGTWVGYQYPGYRGLQYLLEKGDYKDSGDF--gap
QPQVQSVRRIRdmqw
