>1nsnl-1-AUTO.1 | (cluster A) sequence |  111 residues
dIVLTQSPSSLAVSLGQRATISCRASQSVStssFRYMHWYQQKPGQPPRLLIKYASNLESGVPARFSGSGSGTDFTLNIH
PVEEEDTATYYCQHSWEIPYTFGGGTKLEIK
>1acyl-1-DOMAK | (cluster B) sequence |  111 residues
dIVMTQSPASLVVSLGQRATISCRASESVDsygKSFMHWYQQKPGQPPKVLIYIASNLESGVPARFSGSGSRTDFTLTID
PVEADDAATYYCQQNNEDPPTFGAGTKLEMR
>1ggil-1-DOMAK | (cluster B) sequence |  111 residues
dIVLTQSPGSLAVSLGQRATISCRASESVDddgNSFLHWYQQKPGQPPKLLIYRSSNLISGIPDRFSGSGSRTDFTLTIN
PVEADDVATYYCQQSNEDPLTFGAGTKLEIK
>1ibgl-1-AUTO.1 | (cluster B) sequence |  111 residues
-IVLTQSPASLAVSLGQRATISCRASKSVStsgYSHIHWYQQKPGQPPKLLIYLASILESGVPARFSGSGSGTDFTLNIH
PVEEEDAATYYCQHSREYPLTFGAGTELELK
