>1ibgh-1-AUTO.2 | (cluster A) sequence |  123 residues
-vhLVQSGpGLVAPSQSLSITCTVSGFSLTTYGVHWFRQPPGKGLEWLGLIWAGGNTDYNSALMSRLSINKDNSKSQVFL
KMNSLQADDTAMYYCARFRfa-syydYAVDYWGQGTSVTVSSa
>1gigh-1-DOMAK | (cluster B) sequence |  123 residues
qvqLKESGpGLVAPSQSLSITCTVSGFLLISNGVHWVRQPPGKGLEWLGVIWAGGNTNYNSALMSRVSISKDNSKSQVFL
KMKSLQTDDTAMYYCARDFydydvfyYAMDYWGQGTSVTVSS-
>1vfab-1-DOMAK | (cluster B) sequence |  123 residues
qvqLQESGpGLVAPSQSLSITCTVSGFSLTGYGVNWVRQPPGKGLEWLGMIWGDGNTDYNSALKSRLSISKDNSKSQVFL
KMNSLHTDDTARYYCARER------dYRLDYWGQGTTLTVSS-
