>1lmke-1-AS | (cluster A) sequence |  125 residues
-VQLQQSGTELMKPGRSLKISCKTTGYIFSNYWIEWVKQRPGHGLEWIGKILPGGgSNTYNDKFKGKATFTADTSSNIAY
MQLSSLTSEDSAVYYCARGedyyaywyvlDYWGQGTTVTVssggg
>2iffh-1-AUTO.2 | (cluster B) sequence |  125 residues
-VQLQQSGAELMKPGASVKISCKASGYTFSDYWIEWVKQRPGHGLEWIGEILPGSgSTNYHERFKGKATFTADTSSSTAY
MQLNSLTSEDSGVYYCLHGny------dfDGWGQGTTLTVssa--
>2cgrh-1-DOMAK | (cluster B) sequence |  125 residues
rVQLLESGAELMKPGASVQISCKATGYTFSEYWIEWVKERPGHGLEWIGEILPGSgRTNYREKFKGKATFTADTSSNTAY
MQLSSLTSEDSAVYYCTRGys------smDYWGQGTSVTVsaa--
>1mlbb-1-AUTO.1 | (cluster B) sequence |  125 residues
qVQLQESGAEVMKPGASVKISCKATGYTFSTYWIEWVKQRPGHGLEWIGEILPGSgSTYYNEKFKGKATFTADTSSNTAY
MQLSSLTSEDSAVYYCARGdg------nyGYWGQGTTLTVssa--
