>1nsnh-1-AUTO.1 | (cluster A) sequence |  116 residues
DVQLQEsgpGLVKPSQSLSLTCTVTGYSITSdyAWNWIRQFPGNKLEWMGYITYSGTTSYNPSLKSRISISRDTSKNQFF
MQLNSVTTEDTGTFYCTr--gngDWGQGTTLTVSSa
>3hfmh-1-DOMAK | (cluster B) sequence |  116 residues
DVQLQEsgpSLVKPSQTLSLTCSVTGDSITS-dYWSWIRKFPGNRLEYMGYVSYSGSTYYNPSLKSRISITRDTSKNQYY
LDLNSVTTEDTATYYCAn-wdgdYWGQGTLVTVSA-
>1bafh-1-DOMAK | (cluster B) sequence |  116 residues
DVQLQEsgpGLVKPSQSQSLTCTVTGYSITSdyAWNWIRQFPGNKLEWMGYMSYSGSTRYNPSLRSRISITRDTSKNQFF
LQLKSVTTEDTATYFCArgwplaYWGQGTQVSVSEa
