>1ncib-1-AUTO.1 | (cluster A) sequence |  102 residues
gsDWVIPPINLPENSRGPFPQELVRIr------ssLRYSVTGPGADQPPTGIFIINPISGQLSVTKPLDRELIARFHLRA
HAVDINGNQVENPIDIVINVId
>1ncia-1-AUTO.1 | (cluster B) sequence |  102 residues
gsDWVIPPINLPENSRGPFPQELVRIrsgrdknlsLRYSVTGPGADQPPTGIFIINPISGQLSVTKPLDRELIARFHLRA
HAVDINGNQVENPIDIVINVId
>1ncg-1-AUTO.2 | (cluster B) sequence |  102 residues
--DWVIPPINLPENSRGPFPQELVRIrsgrdknlsLRYSVTGPGADQPPTGIFIINPISGQLSVTKPLDRELIARFHLRA
HAVDINGNQVENPIDIVINVI-
