>1apga-2-GJB | (cluster A) sequence |  88 residues
rFQYIEGEMRTRirynRRSAPDPSVITLENSWGRLSTAIQESNQGAFASPIQLQRRNGSKFSVYDVSILIPIIALMVYRC
Apppssqf
>1apa-2-GJB | (cluster B) sequence |  88 residues
-FKYIENQVKTN--fnRAFYPNAKVLNLEESWGKISTAIHNAKNGALTSPLELKNANGSKWIVLRVDDIEPDVGLLKYVN
Gtcqat--
>1pafb-2-GJB | (cluster B) sequence |  88 residues
-FKYIENQVKTN--fnRAFNPNPKVLNLQETWGKISTAIHDAKNGVLPKPLELVDASGAKWIVLRVDEIKPDVALLNYVG
Gscqtt--
