>1typa-3-AS | (cluster A) sequence |  129 residues
KVACAVFSIPPMGVCGYVEEDAAKKY--dQVAVYESSFTPLMHNISGStyKKFMVRIVTNhADGEVLGVHMLGDSSPEII
QSVAICLKMGAKISDFYNTIGVHPTSAEELCSMRtpayfyqkgkrveki
>4gr1-3-AS | (cluster B) sequence |  129 residues
NIPTVVFSHPPIGTVGLTEDEAIHKYgieNVKTYSTSFTPMYHAVTKR-kTKCVMKMVCAnKEEKVVGIHMQGLGCDEML
QGFAVAVKMGATKADFDNTVAIHPTSSEELVTLR---------------
>1gesb-3-AS | (cluster B) sequence |  129 residues
NIPTVVFSHPPIGTVGLTEPQAREQYgddQVKVYKSSFTAMYTAVTTH-rQPCRMKLVCVgSEEKIVGIHGIGFGMDEML
QGFAVALKMGATKKDFDNTVAIHPTAAEEFVTMR---------------
