>1fnf-1-AS.1 | (cluster A) sequence |  100 residues
plsppTNLH-leanpdTGVLTVSWERSTtPDITGYRITTTPTNGqqgnsLEEVVHADQSSCTFDNLSPGLEYNVSVYTVK
d----dkESVPISDTIIPa-
>1fna-1-DOMAK | (cluster B) sequence |  100 residues
-----GSLEvvaa--tPTSLLISWDAPA-VTVRYYRITYGETGGn-spvQEFTVPGSKSTATISGLKPGVDYTITVYAVT
grgdspaSSKPISINYRTei
>1fnf-4-AS.1 | (cluster B) sequence |  100 residues
--dvpRDLEvvaa--tPTSLLISWDAPA-VTVRYYRITYGETGGn-spvQEFTVPGSKSTATISGLKPGVDYTITVYAVT
grgdspaSSKPISINYRT--
