>1cbvh-2-DOMAK | (cluster A) sequence |  102 residues
AKTTPPSVYPLAPgcgdttgsSVTLGCLVKGYFP-eSVTVTWNsgslsSSVHTFPALLQ-sGLYTMSSSVTVPSST-wps
qtVTCSVAHPasstTVDKKLE-
>2mcph-2-DOMAK | (cluster B) sequence |  102 residues
ESARNPTIYPLTLppa-lssdPVIIGCLIHDYFPsgTMNVTWGksgkdITTVNFPPALAsgGRYTMSNQLTLPAVEcpeg
esVKCSVQHDsn-pVQELDVNc
