>1pmy-1-DOMAK | (cluster A) sequence |  123 residues
DEVAVKMLNSGPGGMMVFDPALVRLKPGDSIKFLPTDKGHNVETIKGMAPDGADYVKTTVGQEAVVKFDKEGVYGFKCAP
HYMMGMVALVVVGDkrDNLEAAKSVQHNKLTQKRLDPLFAqiq
>1pzc-1-AUTO.1 | (cluster B) sequence |  123 residues
ENIEVHMLNKGAEGAMVFEPAYIKANPGDTVTFIPVDKGHNVESIKDMIPEGAEKFKSKINENYVLTVTQPGAYLVKCTP
HYAMGMIALIAVGDspANLDQIVSAKKPKIVQERLEKVIAsa-
