>1pnc-1-DOMAK | (cluster A) sequence |  100 residues
-IDVLLGADDGSLAFVPSEFSISPGEKIVFKNNAGFPHNIVFDEDSIPSGVDASKISmseedLLNAKGETFEVALSNKGE
YSFYCSPHQGAGMVGKVTVN
>2plt-1-DOMAK | (cluster B) sequence |  100 residues
dATVKLGADSGALEFVPKTLTIKSGETVNFVNNAGFPHNIVFDEDAIPSGVNADAIS--rddYLNAPGETYSVKLTAAGE
YGYYCEPHQGAGMVGKIIVQ
>7pcy-1-DOMAK | (cluster B) sequence |  100 residues
aAIVKLGGDDGSLAFVPNNITVGAGESIEFINNAGFPHNIVFDEDAVPAGVDADAIS--aedYLNSKGQTVVRKLTTPGT
YGVYCDPHSGAGMKMTITVQ
