>1ptf-1-DOMAK | (cluster A) sequence |  88 residues
mEKKEFHIVAETGIHARPATLLVQTASKFNSDINLEYKGKSVNLKSIMGVMSLGVGQGSDVTITVDGADEAEGMAAIVET
LQKEGLA-
>2hpr-1-DOMAK | (cluster B) sequence |  88 residues
-AQKTFKVTADSGIHARPATVLVQTASKYDADVNLEYNGKTVNLKSIMGVVSLGIAKGAEITISASGADENDALNALEET
MKCEGLGe
>1spha-1-AUTO.1 | (cluster B) sequence |  88 residues
-AQKTFKVTADSGIHARPATVLVQTASKYDADVNLEYNGKTVNLKDIMGVMSLGIAKGAEITISASGADENDALNALEET
MKSEGLGe
