>1crn-1-DOMAK | (cluster A) sequence |  46 residues
TTCCPSIVARSNFNVCRLpgTPEAICATYTGCIIIPGATCPGDYAN
>1cnr-1-DOMAK | (cluster A) sequence |  46 residues
TTCCPSIVARSNFNVCRLpgTPEALCATYTGCIIIPGATCPGDYAN
>1bhp-1-AUTO.1 | (cluster B) sequence |  46 residues
KSCCKSTLGRNCYNLCRA-rGAQKLCANVCRCKLTSGLSCPKDFPK
>2plh-1-AUTO.1 | (cluster B) sequence |  46 residues
KSCCRSTLGRNCYNLCRA-rGAQKLCAGVCRCKISSGLSCPKGFPK
