>1cdla-2-DOMAK | (cluster A) sequence |  73 residues
mkdtdSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYEEFVQMMT--
>4cln-2-DOMAK | (cluster B) sequence |  73 residues
----dSEEEIREAFRVFDKDGNGFISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYEEFVTMMTsk
>1osa-2-GJB | (cluster B) sequence |  73 residues
---qdSEEELIEAFKVFDRDGNGLISAAELRHVMTNLGEKLTDDEVDEMIREADIDGDGHINYEEFVRMMVsk
>3cln-2-DOMAK | (cluster B) sequence |  73 residues
-----SEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREANIDGDGQVNYEEFVQMMTa-
