>1isba-1-GJB | (cluster A) sequence |  95 residues
--SFELPALPYAKDALAPHISAETIEYHYGKHHQTYVTNLNNLIKGt-AFEGKSLEEIIRSs-------eGGVFNNAAQV
WNHTFYWNCLAPnag
>3mdsa-1-DOMAK | (cluster B) sequence |  95 residues
pyPFKLPDLGYPYEALEPHIDAKTMEIHHQKHHGAYVTNLNAALEKypYLHGVEVEVLLRHlaalpqdiqTAVRNNGGGH
LNHSLFWRLLTP---
>1mnga-1-GJB | (cluster B) sequence |  95 residues
pyPFKLPDLGYPYEALEPHIDAKTMEIHHQKHHGAYVTNLNAALEKypYLHGVEVEVLLRHlaalpqdiqTAVRNNGGGH
LNHSLFWRLLTPgg-
