>1pmlb-1-DOMAK | (cluster A) sequence |  88 residues
-DCYFGNGSAYRGTHSLTESGASCLPWNS-miligKVYTAqnpsaQALGLgkHNYCRNPDG-dAKPWCHVLknrrltWEY
CDVPSCst
>1pk4-1-DOMAK | (cluster B) sequence |  88 residues
-DCYHGDGQSYRGTSSTTTTGKKCQSWSSmtph-rHQKTPe--nyPNAGL-tMNYCRNPDA-dKGPWCFTT-dpsvrWEY
CNLKKC--
>1pkr-1-DOMAK | (cluster B) sequence |  88 residues
-ECKTGNGKNYRGTMSKTKNGITCQKWSStsph-rPRFSPa--thPSEGL-eENYCRNPDNdpQGPWCYTT-dpekrYDY
CDILEC--
>2spt-2-DOMAK | (cluster B) sequence |  88 residues
gNCAEGVGMNYRGNVSVTRSGIECQLWRSryph-kPEINSt--thPGADL-rENFCRNPDGsiTGPWCYTT-sptlrREE
CSVPVCg-
