>8i1b-1-DOMAK | (cluster A) sequence |  153 residues
----QLHYRLRDEQQKSLVLSDpYELKALHLngqNINQQVIFSMSFVQGEpsndKIPVALGLKGKNLYLSCVMKDGTPTL
QLESVDPKQYPKKKMEKRFVFNKIEvKSKVEFESAEFPNWYISTSQAEHKPVFLG-nnsgQDIIDFTMESV--
>1hib-1-GJB | (cluster B) sequence |  153 residues
--vrSLNCGLRDSQQKSLVMSGpYELKALHLqgqDMEQQVVFSMSFVQGEesndKIPVALGLKEKNLYLSCVLKDDKPTL
QLESVDPKNYPKKKMEKRFVFNKIE-INKLEFESAQFPNWYISTSQAENMPVFLGgtkggQDITDFTMQFVss
>2i1b-1-DOMAK | (cluster B) sequence |  153 residues
apvrSLNCTLRDSQQKSLVMSGpYELKALHLqgqDMEQQVVFSMSFVQGEesndKIPVALGLKEKNLYLSCVLKDDKPTL
QLESVDPKNYPKKKMEKRFVFNKIEiNNKLEFESAQFPNWYISTSQAENMPVFLGgtkggQDITDFTMQFVss
