>1bsra-1-DOMAK | (cluster A) sequence |  124 residues
-------------dsgnspssssNYCNLMMCCRKMTQGKCKPVNTFVHESLADVKAVCSQKKVTCKNGQTNCYQSKSTMR
ITDCRETGSSKYPNCAYKTTQVEKHIIVACGgkpsvpvhfdasv
>2rns-1-DOMAK | (cluster B) sequence |  124 residues
--------ketaaakferqhmdsNYCNQMMKSRNLTKDRCKPVNTFVHESLADVQAVCSQKNVACKNGQTNCYQSYSTMS
ITDCRETGSSKYPNCAYKTTQANKHIIVACEgnpyvpvhfdasv
>1ssaa-1-DOMAK | (cluster B) sequence |  124 residues
ketaaakferqhmdsstsaasssNYCNQMMKSRNLTKDRCKPVNTFVHESLADVQAVCSQKNVACKNGQTNCYQSYSTMS
ITDCRETGSSKYPNCAYKTTQANKHIIVACEgn-----------
>5rsa-1-AS | (cluster B) sequence |  124 residues
ketaaakferqhmdsstsaasssNYCNQMMKSRNLTKDRCKPVNTFVHESLADVQAVCSQKNVACKNGQTNCYQSYSTMS
ITDCRETGSSKYPNCAYKTTQANKHIIVACEgnpyvpvhfdasv
